name: Mirror Dockerhub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: adguard/adguardhome
            repo: docker.io
          - image: b4bz/homer
            repo: docker.io
          - image: budibase/budibase
            repo: docker.io
          - image: filerun/filerun
            repo: docker.io
          - image: jhpyle/docassemble
            repo: docker.io
          - image: kcollins/ignition
            repo: docker.io
          - image: meisnate12/plex-meta-manager
            repo: docker.io
          - image: nodered/node-red
            repo: docker.io
          - image: pawelmalak/flame
            repo: docker.io
          - image: saspus/duplicacy-web
            repo: docker.io
          - image: lukevella/rallly
            repo: docker.io
          - image: ghost
            repo: docker.io
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v5
      - uses: imjasonh/setup-crane@v0.3
      - name: Mirror
        run: |
          for tag in $(cat ./images/${{ matrix.image }}); do
            crane copy \
              ${{ matrix.repo }}/${{ matrix.image }}:$tag \
              ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:$tag
          done
